version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: navalinJGM10
      MYSQL_DATABASE: tenis_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tenis_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: navalinJGM10
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
